#!/bin/bash

sudo sh -c 'echo 132 > /sys/class/gpio/export'
sudo sh -c 'echo 133 > /sys/class/gpio/export'
sudo sh -c 'echo 134 > /sys/class/gpio/export'
sudo sh -c 'echo 135 > /sys/class/gpio/export'
sudo sh -c 'echo 136 > /sys/class/gpio/export'
sudo sh -c 'echo 137 > /sys/class/gpio/export'
sudo sh -c 'echo 138 > /sys/class/gpio/export'
sudo sh -c 'echo 139 > /sys/class/gpio/export'
